const ifcTypes = {
  IfcProject: "IFCPROJECT",
  IfcSite: "IFCSITE",
  IfcBuildingStorey: "IFCBUILDINGSTOREY",
  IfcBuilding: "IFCBUILDING",
  IfcSpace: "IFCSPACE",
  // IfcWallStandardCase: "IFCWALLSTANDARDCASE",
  // IfcWall: "IFCWALL",
  // IfcDoor: "IFCDOOR",
  // IfcSlab: "IFCSLAB",
  // IfcGeometricRepresentationContext: "IFCGEOMETRICREPRESENTATIONCONTEXT",
  // IfcAxis2Placement3D: "IFCAXIS2PLACEMENT3D",
  // IfcCartesianPoint: "IFCCARTESIANPOINT",
  // IfcDirection: "IFCDIRECTION",
  // IfcLocalPlacement: "IFCLOCALPLACEMENT",
  // IfcGridPlacement: "IFCGRIDPLACEMENT",
  // IfcLinearPlacement: "IFCLINEARPLACEMENT",
  // IfcApplication: "IFCAPPLICATION",
  // IfcOrganization: "IFCORGANIZATION",
  // IfcOwnerHistory: "IFCOWNERHISTORY",
  // IfcRelAggregates: "IFCRELAGGREGATES",
  // IfcRelContainedInSpatialStructure: "IFCRELCONTAINEDINSPATIALSTRUCTURE",
  // IfcConversionBasedUnit: "IFCCONVERSIONBASEDUNIT",
  // IfcDerivedUnitElement: "IFCDERIVEDUNITELEMENT",
  // IfcDerivedUnit: "IFCDERIVEDUNIT",
  // IfcMeasureWithUnit: "IFCMEASUREWITHUNIT",
  // IfcSIUnit: "IFCSIUNIT",
  // IfcUnitAssignment: "IFCUNITASSIGNMENT",
};

export { ifcTypes };
